### PR TITLE
Add back missing peptides with reindex()

### PR DESCRIPTION
**Pull request by sminot**
I made this because Pritha came across a bug which I think was causing a problem because some of the peptides from the library hadn't been sequenced across any of the samples. Does this look like a reasonable modification of your code for merging the data?

### CODE REVIEW

**Comment by jgallowa07** [comment]
Ah, yes this is something we didn't really worry about with our smaller libraries. This seems okay, I'm a little confused how
```
    merged_counts_df = pd.DataFrame({
        int(os.path.basename(path).split(".")[0]): load(path)
        for path in counts
    }).fillna(0)
```
makes sure that the peptide id's are lined between samples .... could you elaborate?

**Comment by sminot** [comment]
Ah yes, I actually included two changes in this PR. The changes in `stitch_dataset` are used to add back missing peptide IDs (with the `.reindex()` call).

The construction of `merged_counts_df` is something I did to get rid of the `reduce` call, which I _believe_ is creating intermediate DataFrames with each additional column which is joined, rather than just creating a DataFrame once. This is something I can test out more, though, to justify the change. 

I need to do more testing on my end to make sure I understand the error that we encountered that I made this to fix. I'll update you once I've figured it out more.

**Review by jgallowa07 — APPROVED** [review]
Oh I see what you did here. This looks good to me!!

**Comment by sminot** [comment]
I figured out that the error which sent me down this path was actually being caused by an inappropriately-formatted library file. While the changes in this PR may be good in principle, without a motivating use-case I'd rather stick to the principle of if-it-aint-broke-dont-fix-it

**Pull request closed without merging**
